version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_BASE_URL=/api
      - WDS_SOCKET_PORT=0
    command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --root-path /api

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  node_modules: